name: drupal11-starter
recipe: drupal11

config:
  webroot: web
  via: nginx:1.25
  php: '8.4'
  xdebug: true
  database: mysql:8.4

services:
  mailhog:
    type: mailhog
    portforward: true

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  
  solrserver:
    type: solr:9
    portforward: true

tooling:
  composer:
    service: appserver
    cmd: composer

  xdebug-on:
    service: appserver
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root

  xdebug-off:
    service: appserver
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
